# -*- coding: utf-8 -*-
"""
gen_font.py — 生成 OLED 用的 16x16 中文点阵 + 8x16 ASCII 字库 (oled_font.h)

用法:
    py gen_font.py [姓名]

  公开版默认显示隐私别名“张三”。

字模格式:
  中文 16x16: 32 字节/字, 行扫描、每行 2 字节、高位在左 (row-major, MSB=最左像素)
  ASCII 8x16: 16 字节/字符, 行扫描、每行 1 字节、高位在左
"""
import sys
from pathlib import Path
from PIL import Image, ImageDraw, ImageFont

# ---- 需要的中文集合（界面全部文案的字符合集）----
NAME = sys.argv[1] if len(sys.argv) > 1 else "张三"

CN_CHARS = "".join(sorted(set(NAME + "占空比状态正反转停止时间电机常运作速度异常")))

CN_FONT_PATH = r"C:\Windows\Fonts\simhei.ttf"    # 黑体

# 界面用字的拼音名 (用于生成 C 枚举常量名)
PINYIN = {"占":"ZHAN","空":"KONG","比":"BI","状":"ZHUANG","态":"TAI","正":"ZHENG",
          "转":"ZUAN","停":"TING","止":"ZHI","时":"SHI","间":"JIAN","电":"DIAN",
          "机":"JI","常":"CHANG","运":"YUN","作":"ZUO","速":"SU","度":"DU",
          "异":"YI","反":"FAN","张":"ZHANG","三":"SAN"}
ASCII_FONT_PATH = r"C:\Windows\Fonts\consola.ttf"  # Consolas (等宽, 窄)

ASCII_FIRST = 0x20
ASCII_COUNT = 95


def render_cn(ch):
    """16x16, 4x 过采样后降采样, 阈值 128"""
    S = 4
    font = ImageFont.truetype(CN_FONT_PATH, 16 * S)
    img = Image.new("L", (16 * S, 16 * S), 0)
    d = ImageDraw.Draw(img)
    bbox = d.textbbox((0, 0), ch, font=font)
    w = bbox[2] - bbox[0]
    h = bbox[3] - bbox[1]
    d.text(((16 * S - w) / 2 - bbox[0], (16 * S - h) / 2 - bbox[1]), ch, font=font, fill=255)
    img = img.resize((16, 16), Image.LANCZOS)
    px = img.load()
    rows = []
    for y in range(16):
        b0 = b1 = 0
        for x in range(8):
            if px[x, y] > 100:
                b0 |= 0x80 >> x
            if px[8 + x, y] > 100:
                b1 |= 0x80 >> x
        rows.append(b0)
        rows.append(b1)
    return rows


def render_ascii(ch):
    """8x16: 从 16 号开始, 若超宽则逐步缩小字号直至放入 8 像素宽"""
    cell_w, cell_h = 8, 16
    for size in range(16, 9, -1):
        font = ImageFont.truetype(ASCII_FONT_PATH, size)
        img = Image.new("L", (cell_w, cell_h), 0)
        d = ImageDraw.Draw(img)
        try:
            bbox = d.textbbox((0, 0), ch, font=font)
        except Exception:
            bbox = (0, 0, cell_w, cell_h)
        w = bbox[2] - bbox[0]
        if w <= cell_w:
            ascent, descent = font.getmetrics()
            y0 = max(0, (cell_h - (ascent + descent)) // 2)
            d.text(((cell_w - w) / 2 - bbox[0], y0 - bbox[1]), ch, font=font, fill=255)
            if ch == ".":
                # 句点必须落在基线上, 否则渲染成上标点并与前一位数字重叠
                d.rectangle((0, 0, cell_w, cell_h), fill=0)
                d.rectangle((3, 12, 4, 13), fill=255)
            px = img.load()
            rows = []
            for y in range(cell_h):
                b = 0
                for x in range(cell_w):
                    if px[x, y] > 100:
                        b |= 0x80 >> x
                rows.append(b)
            return rows
    raise RuntimeError("glyph too wide: %r" % ch)


def ascii_art(rows, w):
    out = []
    for i, b in enumerate(rows):
        line = "".join("#" if b & (0x80 >> x) else "." for x in range(w))
        out.append(line)
    return out


def main():
    cn_glyphs = {}
    for ch in CN_CHARS:
        cn_glyphs[ch] = render_cn(ch)

    ascii_glyphs = [render_ascii(chr(c)) for c in range(ASCII_FIRST, ASCII_FIRST + ASCII_COUNT)]

    # ---- 输出 ----
    lines = []
    a = lines.append
    a("/* oled_font.h - auto-generated by tools/gen_font.py - do not edit */")
    a("/* PUBLIC DISPLAY ALIAS: %s  (edit tools/gen_font.py, regen, rebuild) */"
      % " ".join("U+%04X" % ord(c) for c in NAME))
    a("#ifndef OLED_FONT_H")
    a("#define OLED_FONT_H")
    a("")
    a("#include <stdint.h>")
    a("")
    a("#define OLED_ASCII_FIRST  0x%02X" % ASCII_FIRST)
    a("#define OLED_ASCII_COUNT  %d" % ASCII_COUNT)
    a("")
    a("/* ASCII 8x16,  */")
    a("static const uint8_t OLED_ASCII_8x16[OLED_ASCII_COUNT][16] = {")
    for i, g in enumerate(ascii_glyphs):
        ch = chr(ASCII_FIRST + i)
        hexs = ", ".join("0x%02X" % b for b in g)
        name = ("'%s'" % ch) if ch not in ("\\", "'") else ("'\\\\'" if ch == "\\" else "'\\''")
        a("    {%s}, /* %3d %s */" % (hexs, i, name if ch != " " else "space"))
    a("};")
    a("")
    a("/* CN glyphs 16x16, row-major, MSB-left; index = cn_glyph_t */")
    a("typedef enum {")
    for i, ch in enumerate(CN_CHARS):
        a("    CN_%s = %d,  /* U+%04X */" % (PINYIN.get(ch, "x%04X" % ord(ch)), i, ord(ch)))
    a("    CN_NUM")
    a("} cn_glyph_t;")
    a("")
    a("static const uint8_t OLED_CN_16x16[CN_NUM][32] = {")
    for i, ch in enumerate(CN_CHARS):
        g = cn_glyphs[ch]
        rows = [", ".join("0x%02X" % b for b in g[j:j + 8]) for j in range(0, 32, 8)]
        a("    { /* U+%04X */" % ord(ch))
        for r in rows:
            a("        %s," % r)
        a("    },")
    a("};")
    a("")
    a("#endif /* OLED_FONT_H */")
    a("")

    project_root = Path(__file__).resolve().parents[1]
    for proj in ("A", "B"):
        path = project_root / "Firmware" / proj / "Core" / "Inc" / "oled_font.h"
        text = "\n".join(lines)
        bad = sorted(set(c for c in text if ord(c) > 127))
        if bad:
            print("NON-ASCII DROPPED:", bad)
        with open(path, "w", encoding="ascii", errors="ignore") as f:
            f.write(text)
        print("written:", path)

    # ---- 终端预览（自检）----
    print("\n== 预览: %s ==" % NAME)
    for ch in NAME:
        print(" ".join(ascii_art(cn_glyphs[ch], 16)[y] for y in range(0, 16, 2)) + "   " + ch)
    print("\n== 预览: '0123%' ==")
    for ch in "0123%":
        print(" ".join(ascii_art(ascii_glyphs[ord(ch) - ASCII_FIRST], 8)[y] for y in range(0, 16, 2)) + "  " + ch)


if __name__ == "__main__":
    main()
